version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: projek_nest_bang
      POSTGRES_DB: db_archive
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: archive_app
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app_network
      
  redis:
    image: redis:7-alpine
    container_name: curveball_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
