services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: projek_nest_bang
      POSTGRES_DB: db_archive
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nest"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: archive_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: archive_app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    # ports:
    #   - "5000:5000"
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - .:/usr/src/app
    command: sh -c "yarn install && yarn start:dev"

  nginx:
    image: nginx:alpine
    container_name: archive_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl  # optional, untuk SSL certs nanti
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
